# Generated by Django 5.2.16 on 2026-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('vendedor', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('produto', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('meta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
